/**
 * Project data. Copy is drafted from published coverage — replace with final text + real imagery.
 * `gallery` entries are used by the horizontal project view (cover → brief → images → next).
 */
export const PROJECTS = [
  {
    id: "pregame",
    title: "Pregame",
    kicker: "Concept Store & Bar",
    location: "Bengaluru, India",
    year: "2025",
    image: "img/pregame.jpg",
    tint: "#3a2a1c",
    facts: { Typology: "Retail + Bar", Area: "10,000 sq ft · 2 levels", Year: "2025", Featured: "ArchDaily · ELLE Decor · Interior Design" },
    statement: "Carved, not built.",
    text: "Drawing from subterranean architecture, Egyptian cave formations, excavation logics and ancient carved spaces, Pregame synchronises a retail store and a pub into one sculpted, maze-like interior. A difficult shell becomes a cavernous spatial narrative that moves guests from browsing to dining to nightlife without ever leaving the cave.",
    gallery: [
      { src: "img/pregame.jpg", caption: "Arrival — the carved threshold between street and store" },
      { src: "img/residence.jpg", caption: "Retail level — niches cut into the mass hold product like artefacts" },
      { src: "img/lucifers-lair.jpg", caption: "Lower level bar — the cave narrows, the light turns amber" },
    ],
    materials: ["Sculpted micro-concrete", "Sand-cast plaster", "Oxidised brass", "Smoked oak"],
  },
  {
    id: "lucifers-lair",
    title: "Lucifer’s Lair",
    kicker: "Restobar",
    location: "Bengaluru, India",
    year: "2024",
    image: "img/lucifers-lair.jpg",
    tint: "#3b0f12",
    facts: { Typology: "Restobar", Palette: "Dark marble · fire & water", Featured: "ELLE Decor India" },
    statement: "Where temptation meets tranquillity.",
    text: "An immersive, underworld-inspired interior built on the duality of heaven and hell. Lucifer’s Lair plays with the tension between fire and water: dark, rippling marble conjures a still moonlit lake while a bold, dramatic material palette carries the heat.",
    gallery: [
      { src: "img/lucifers-lair.jpg", caption: "The lake — rippled black marble under a low ceiling of flame-toned light" },
      { src: "img/pregame.jpg", caption: "Bar front — fire side, with heat-blued steel" },
      { src: "img/residence.jpg", caption: "Private booths carved into the perimeter" },
    ],
    materials: ["Nero Marquina marble", "Blackened steel", "Burnt-red velvet", "Hand-glazed terracotta"],
  },
  {
    id: "knossos",
    title: "Knossos",
    kicker: "Private Residence",
    location: "Dubai, UAE",
    year: "2024",
    image: "img/knossos.jpg",
    tint: "#5c564a",
    facts: { Typology: "Residence", Area: "2,300 m²", Status: "Private" },
    statement: "A palace plan, quietly reinterpreted.",
    text: "A 2,300 square metre residence conceived as a sequence of courts and thresholds. Pale stone, deep shade and long sightlines structure a home that is monumental in scale yet intimate in its rooms.",
    gallery: [
      { src: "img/knossos.jpg", caption: "Entry court — limestone, shade and a single line of water" },
      { src: "img/studio.jpg", caption: "The long gallery that threads the private wings" },
      { src: "img/tech-park.jpg", caption: "Evening — the courtyards read as lanterns" },
    ],
    materials: ["Jordanian limestone", "Travertine", "Bronze", "Lime plaster"],
  },
  {
    id: "school-lobby",
    title: "Take Flight",
    kicker: "Primary School Lobby",
    location: "Bengaluru, India",
    year: "2023",
    image: "img/school-lobby.jpg",
    tint: "#6b4a30",
    facts: { Typology: "Education", Scope: "Lobby & arrival", Featured: "ELLE Decor India" },
    statement: "Where aspirations take flight.",
    text: "An arrival space designed to lift the first moment of every school day. Warm colour, soft geometry and playful scale meet a durable, child-first material strategy.",
    gallery: [
      { src: "img/school-lobby.jpg", caption: "Arrival — the ceiling installation of folded ‘wings’" },
      { src: "img/knossos.jpg", caption: "Reading nooks at child height" },
    ],
    materials: ["Powder-coated aluminium", "Rubber flooring", "Birch ply", "Cork"],
  },
  {
    id: "tech-park",
    title: "Tech Park",
    kicker: "Workplace",
    location: "Bengaluru, India",
    year: "2023",
    image: "img/tech-park.jpg",
    tint: "#1e3034",
    facts: { Typology: "Workplace", Approach: "Open floor plans · Natural light", Scope: "Masterplan to interiors" },
    statement: "Daylight first.",
    text: "Workspaces that put daylight and movement first. Open floor plans, generous breakout spaces and embedded technology shape environments where teams want to be, designed to flex as the organisations inside them grow.",
    gallery: [
      { src: "img/tech-park.jpg", caption: "The atrium — a full-height daylight well" },
      { src: "img/studio.jpg", caption: "Floorplate — open, with acoustic ‘rooms within rooms’" },
    ],
    materials: ["Exposed concrete", "Low-iron glass", "Acoustic felt", "Living green walls"],
  },
  {
    id: "residence",
    title: "Private Residence",
    kicker: "Ultra-luxury",
    location: "Confidential",
    year: "2022",
    image: "img/residence.jpg",
    tint: "#3a2e24",
    facts: { Typology: "Residence", Client: "Private", Scope: "Architecture + Interiors + Objects" },
    statement: "One authored piece.",
    text: "For ultra-high-net-worth clients the brief is never only a house. Each residence is composed end to end, from site strategy and structure through to furniture, lighting and art, so that the whole reads as one authored piece.",
    gallery: [
      { src: "img/residence.jpg", caption: "Living hall — bronze, walnut and a ten-metre window" },
      { src: "img/pregame.jpg", caption: "Bespoke furniture and lighting, all by the studio" },
    ],
    materials: ["Walnut", "Patinated bronze", "Silk plaster", "Basalt"],
  },
];
